-- Bambu Vibe ERD schema
-- PostgreSQL / Supabase SQL

create table if not exists category (
    category_id bigint generated by default as identity primary key,
    category_name varchar(150) not null unique,
    description varchar(255)
);

create table if not exists supplier (
    supplier_id bigint generated by default as identity primary key,
    supplier_name varchar(150) not null,
    contact_person varchar(150),
    phone varchar(50),
    email varchar(150),
    address varchar(255),
    status varchar(50) not null default 'active'
);

create table if not exists "user" (
    user_id bigint generated by default as identity primary key,
    full_name varchar(150) not null,
    role varchar(50) not null default 'staff',
    username varchar(100) not null unique,
    password varchar(255) not null,
    is_active boolean not null default true
);

create table if not exists item (
    item_id bigint generated by default as identity primary key,
    item_name varchar(150) not null unique,
    unit_type varchar(50) not null,
    unit_cost numeric(12,2) not null default 0,
    quantity_on_hand int not null default 0
);

create table if not exists product (
    product_id bigint generated by default as identity primary key,
    product_name varchar(150) not null unique,
    category_id bigint not null references category(category_id) on update cascade,
    unit varchar(50) not null,
    reorder_level int not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists sales (
    sale_id bigint generated by default as identity primary key,
    sale_date date not null default current_date,
    user_id bigint not null references "user"(user_id) on update cascade
);

create table if not exists sales_details (
    sale_detail_id bigint generated by default as identity primary key,
    sale_id bigint not null references sales(sale_id) on delete cascade on update cascade,
    product_id bigint not null references product(product_id) on update cascade,
    quantity int not null check (quantity > 0),
    price numeric(12,2) not null check (price >= 0)
);

create table if not exists ingredients (
    product_id bigint not null references product(product_id) on delete cascade on update cascade,
    item_id bigint not null references item(item_id) on update cascade,
    unit_type varchar(50) not null,
    quantity_needed int not null check (quantity_needed > 0),
    primary key (product_id, item_id, unit_type)
);

create table if not exists supply (
    supply_id bigint generated by default as identity primary key,
    supply_date date not null default current_date,
    supplier_id bigint not null references supplier(supplier_id) on update cascade,
    user_id bigint not null references "user"(user_id) on update cascade
);

create table if not exists supply_details (
    supply_detail_id bigint generated by default as identity primary key,
    supply_id bigint not null references supply(supply_id) on delete cascade on update cascade,
    item_id bigint not null references item(item_id) on update cascade,
    unit_type varchar(50) not null,
    quantity int not null check (quantity > 0),
    price numeric(12,2) not null check (price >= 0)
);

create table if not exists stock_out (
    stockout_id bigint generated by default as identity primary key,
    user_id bigint not null references "user"(user_id) on update cascade,
    stockout_date date not null default current_date,
    reason varchar(255)
);

create table if not exists stock_out_product (
    stockout_product_id bigint generated by default as identity primary key,
    stockout_id bigint not null references stock_out(stockout_id) on delete cascade on update cascade,
    product_id bigint not null references product(product_id) on update cascade,
    quantity int not null check (quantity > 0),
    cost numeric(12,2) not null check (cost >= 0)
);

create table if not exists stock_out_item (
    stockout_item_id bigint generated by default as identity primary key,
    stockout_id bigint not null references stock_out(stockout_id) on delete cascade on update cascade,
    item_id bigint not null references item(item_id) on update cascade,
    quantity int not null check (quantity > 0),
    cost numeric(12,2) not null check (cost >= 0)
);

create table if not exists expiration (
    expiration_id bigint generated by default as identity primary key,
    item_id bigint not null references item(item_id) on delete cascade on update cascade,
    unit_type varchar(50) not null,
    unit_quantity int not null check (unit_quantity > 0),
    expiration_date date not null
);
